apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    domain: etl
    environment: production
    team: demo
  name: kafka
  namespace: argocd
spec:
  destination:
    namespace: kafka
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    helm:
      valueFiles:
        - values.yaml
    repoURL: git@github.com:adam-cv/minikube-cluster
    path: deploy/charts/kafka
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true