apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    domain: etl
    environment: production
    team: monitoring
  name: prometheus
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 61.3.0
    chart: kube-prometheus-stack
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true 
